ucfyao/moow-web-next

README.md

This PR adds the project introduction section to the README file. The new section provides an overview of the Xiaobao platform.

Add the project introduction part to the README file

---

package.json
src/app/addmarket/addmarket.css
src/app/addmarket/page.tsx

Add exchangekey list page tsx and css file.

feat: #606 add exchangekey list page

---

src/app/market/page.tsx

Add the basic html structure of the get exchangekey list page

feat: #605 add show exchangekey list page

---

src/app/activate/page.tsx
src/styles/activate.css

adding the page.tsx for the activation email function. It's weird there are two commits.

feat: #405 activate page

---

package.json
src/app/strategy/newStrategy/page.jsx

feat(strategy): Add HTML and partial CSS for new strategy page
This PR introduces the initial HTML structure and partial CSS styling for the new strategy page. The main layout elements and essential classes have been defined to provide a foundation for further development.
Added HTML structure for the new strategy page
Implemented initial CSS for layout and styling
Updated dependencies in package.json

feat: #505 new strategy tem

---

src/app/activate/[userId]/page.tsx

According to Jack's document "From Vue to Next: Hands on Turotial" on Lark, I use dynamic router since userId is a dynamic parameter.

refactor: #407 refacor the router of activate email 

---

src/app/strategy/newStrategy/page.jsx

feat(strategy): add style to NewStrategy component
This PR adds custom CSS styling to the NewStrategy component to improve its appearance and ensure consistent design across the application.
- Created a NewStrategy.module.css file containing scoped CSS classes.
- Updated NewStrategy component to use CSS Modules for styling.
new strategy css

feat: #516 new strategy css

---

src/app/strategy/newStrategy/NewStrategy.module.css

feat(strategy): add style to NewStrategy component
This PR updated NewStrategy.module.css file containing scoped CSS classes to the NewStrategy component. 
new strategy css

feat: #517 new strategy css

---

src/app/layout.tsx
src/app/market/page.tsx

1. Delete the use of antd and other useless import
2. Add the navigate link from home page to market, and add the navigate on the button add api key

feat: #605: Add home page nav link and the add api key nav logic

---

src/app/layout.tsx
src/app/login/page.tsx

fix captcha and some link issues.
Issues remain to be solved due to technical reasons:
1. frontend can obtain response from backend API, but how to deal with the response has not been done because the signup page is still undo review.
2. The redux part has been commented ('//') because the store Provider function is still been processed by the owner.

refactor: #406 fix some problem of previous login page

---

src/app/globals.scss
src/app/layout.tsx
src/app/page.tsx

fix(assets/images): update the paths of images
Updated the image paths to ensure that all images are correctly referenced and displayed.

fix: #521 images path

---

src/app/login/page.tsx

change the path of globals and some spelling errors

fix: #406 fix the path of globals

---

src/app/strategies/page.tsx
src/app/styles/strategies.module.css
src/component/pagination.tsx

1. Updated css of the strategy list page
2. Added pagination component
3. Implemented pagination functions

feat:#509 updated strategy page css and pager

---

src/app/newStrategy/page.tsx

feat(NewStrategy): data validation and form submission
This PR enhances the NewStrategy component with the following changes:
1. Modified the input elements to correctly display placeholders.
2. Refactored the period value from three separate arrays into a single array. This change allows for correct storage of the period value in both form data and invalid fields.
3. Implemented robust form data validation to ensure that all required fields are correctly filled out before submission. 
4. Enhanced the form submission process to ensure that all form data is correctly captured and submitted.

feat: #523 new strategy data validation and form submission

---

src/app/newStrategy/page.tsx

feat: #524 Add Edit and Delete Strategy Functions
- Implemented the ability to edit existing strategies. 
- Added the option to delete strategies. 
- Rename planId to strategyId for better consistency with other components. 
newStrategy

feat: #524 edit and delete strategy

---

src/app/strategies/[strategyId]/page.tsx
src/component/pagination.tsx
src/pages/strategies/index.tsx

1. Added i18n for strategies page
2. Moved strategies to pages directory
3. Added config to store constants, fixed some relative paths

feat:#512 Moved strategies to pages directory with i18n

---

src/app/aip/addstrategy/page.tsx

fix(newStrategy): issues detected by the plugin
This PR addresses several issues in the newStrategy component detected by the plugin:
- Reorganized certain parts of the code.
- Converted Function Expressions to Function Declarations for better hoisting and clarity.
- Defined log and logError functions to ensure console messages are only printed in the development environment.
- Updated App Router to align with the updated routing logic.
- Added <button> elements within <li> elements to improve onClick event handling.

fix: #526 new strategy

---

src/app/aip/page.tsx
src/components/Pagination.tsx

fix(strategy list)
This PR addresses several bugs on the strategy list page that arose after integrating new plugins, including:
- Completed switchStrategyStatus method.
- Modified the navigation links to align with the new directory structure.
- Changed the onClick event binding from <li> to <button> to ensure proper event handling.
- Converted function expressions to function declarations for better readability and maintainability.

fix: #527: strategy list

---

src/app/aip/addmarket/page.tsx

Fix the bugs in the addmarket page.

fix #611 debug of the addmarket page

---

package.json
src/app/activate/[userId]/page.tsx
src/app/login/page.tsx
src/store/index.ts
src/store/user.ts
src/utils/auth.js

- Define the sendActivateEmail function:Set a countdown timer to 60 seconds and disabled the button. Sent a POST request to /api/v1/auth/activation to send the activation email, setting different alert messages upon success or failure.Displayed the alert messages using Snackbar.
- Define the handleClose function:Closed the Snackbar.
- Manage the countdown logic with useEffect:Decreased the timerCounter by 1 every second if it's greater than 0.Enabled the button when the countdown ends.Render the component:
- Defined styles using css.Used Snackbar to display alert messages.Rendered a section containing activation information and a button.

422 fix activate debug

---

src/app/activeConfirm/[token]/page.tsx

feat: #423 activeconfirm page

---

.vscode/settings.json
src/app/aip/addmarket/page.tsx

Fulfill and continue writing the addmarket page.

feat: #612 continue add market page

---

src/app/aip/addstrategy/page.tsx
src/app/aip/page.tsx

feat(addstrategy): integration with backend

feat: #529 addstrategy integration

---

src/app/aip/[strategyId]/page.tsx

feat(strategy): strategy order detail integration
This PR addresses several improvements and fixes to the strategy detail and order list page:
(1) Data Types Alignment: Modified data types to ensure consistency with the legacy project code and the new project's API documentation.
(2) Destructuring Assignment Fixes: Adjusted destructuring assignments to correctly retrieve data, improving the accuracy and functionality of the code.
(3) Mock Data Removal: Removed Chart-related mock data to enhance code cleanliness and maintainability.

feat: #531 strategy order detail integration

---

package.json
src/app/page.tsx

added swiper, but ain't add CDN. CDN will be in a separate PR.

feat: #610 add banner swiper
